import{a as P,S as R,i as d}from"./assets/vendor-5YrzWRhu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const q="51587932-ec02964f1d63236ab83378a4f",B="https://pixabay.com/api/",$=15;async function p(r,t=1){return(await P.get(B,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:$,page:t}})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),M=new R(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const t=r.map(({webformatURL:a,largeImageURL:c,tags:e,likes:o,views:s,comments:S,downloads:E})=>`
    <li class="gallery-item">
      <a href="${c}">
        <img src="${a}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${S}</p>
        <p><b>Downloads:</b> ${E}</p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",t),M.refresh()}function A(){m.innerHTML=""}function L(){h.classList.remove("is-hidden")}function n(){h.classList.add("is-hidden")}function b(){y.classList.remove("is-hidden")}function u(){y.classList.add("is-hidden")}const v=document.querySelector(".form"),H=v.querySelector(".input"),O=document.querySelector(".load-more");let l="",i=1,f=0;const w=15;v.addEventListener("submit",async r=>{if(r.preventDefault(),l=H.value.trim(),!!l){i=1,A(),u(),L();try{const t=await p(l,i);if(f=t.totalHits,t.hits.length===0){d.info({message:"Sorry, no images found. Try another word.",position:"topRight"}),n();return}g(t.hits),n(),f>i*w&&b()}catch{d.error({message:"Error fetching images",position:"topRight"}),n()}}});O.addEventListener("click",async()=>{i+=1,L(),u();try{const r=await p(l,i);g(r.hits),n(),_(),i*w>=f?(d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),u()):b()}catch{d.error({message:"Error loading more images",position:"topRight"}),n()}});function _(){const r=document.querySelector(".gallery-item");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
