import{a as q,S as B,i as d}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const E="51587932-ec02964f1d63236ab83378a4f",R="https://pixabay.com/api/",P=15;async function p(r,o=1){return(await q.get(R,{params:{key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:o}})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),$=new B(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const o=r.map(({webformatURL:a,largeImageURL:c,tags:e,likes:t,views:s,comments:w,downloads:S})=>`
    <li class="gallery-item">
      <a href="${c}">
        <img src="${a}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${t}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${w}</p>
        <p><b>Downloads:</b> ${S}</p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",o),$.refresh()}function M(){m.innerHTML=""}function L(){h.classList.remove("is-hidden")}function n(){h.classList.add("is-hidden")}function b(){y.classList.remove("is-hidden")}function u(){y.classList.add("is-hidden")}const v=document.querySelector(".form"),H=v.querySelector(".input"),O=document.querySelector(".load-more");let l="",i=1,f=0;v.addEventListener("submit",async r=>{if(r.preventDefault(),l=H.value.trim(),!!l){i=1,M(),u(),L();try{const o=await p(l,i);if(f=o.totalHits,o.hits.length===0){d.info({message:"Sorry, no images found. Try another word.",position:"topRight"}),n();return}g(o.hits),n(),f>i*15&&b()}catch{d.error({message:"Error fetching images",position:"topRight"}),n()}}});O.addEventListener("click",async()=>{i+=1,L(),u();try{const r=await p(l,i);g(r.hits),n(),A(),i*15>=f?(d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),u()):b()}catch{d.error({message:"Error loading more images",position:"topRight"}),n()}});function A(){const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
